### ISSUE TITLE
Environment variable to clear cache on start

### ISSUE THREAD

**Issue by arjenfvellinga** [jgeusebroek/docker-spotweb#22]
Is it possible for you to add a boolean environment variable that execute the following command on startup:

`root@spotweb:/var/www/spotweb/bin# php upgrade-db.php --clear-cache -yes`

**Comment by jgeusebroek** [comment]
I could, but would it not be easier to just run in inside the container? Since this isn't something you'd be doing regularly. 
docker exec spotweb /usr/bin/php /var/www/spotweb/bin/upgrade-db.php --clear-cache -yes

Also, when the image is replaced with a newer version, the cache will be cleared because of the new container.

**Comment by arjenfvellinga** [comment]
True, that I don't know how often I would want to execute this. I don't restart the dockers that often, so for me clearing the cache at restart would not be that ok. But I'm fine to make a cron job on my machine for this.

**Comment by jgeusebroek** [comment]
OK, great. I'm closing this issue.
